# Generated by Django 2.0.5 on 2018-05-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminPerson',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_adminPerson',
        ),
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
