# Generated by Django 2.0.5 on 2018-07-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Habilitado'), (2, 'No habilitado')], default=1, null=True),
        ),
    ]
