# Generated by Django 2.0.5 on 2018-05-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0002_auto_20180517_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminPerson',
            new_name='Manager',
        ),
    ]
