# Generated by Django 2.1a1 on 2018-06-05 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0003_auto_20180529_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_adminPerson',
            new_name='is_manager',
        ),
    ]
