# Generated by Django 2.0.3 on 2018-07-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichaArticulo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='imgfile',
            new_name='image',
        ),
    ]
