# Generated by Django 2.0.3 on 2018-07-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaArticulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechadereserva',
            name='id',
            field=models.CharField(default='8d426456b9ba4f66af5672528383d7da', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default='5ab95db497b2430fb4f6dc328a5b4f0e', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
