# Generated by Django 2.0.3 on 2018-07-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaArticulo', '0002_auto_20180704_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, upload_to='fichaArticulo/static/css'),
        ),
    ]
