# Generated by Django 2.0.5 on 2018-07-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaArticulo', '0002_auto_20180709_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechadereserva',
            name='id',
            field=models.CharField(default='07d3ddaf12664b18bf215064603a1a33', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default='a9f6971737b1424eb0d9bf6cb349e543', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
