# Generated by Django 2.0.3 on 2018-07-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaArticulo', '0004_auto_20180709_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechadereserva',
            name='id',
            field=models.CharField(default='798209fb8f9247b39d0550b4e2c23879', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default='fe6b109007654697a8599df7aa39fc6e', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
