# Generated by Django 2.0.5 on 2018-07-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaArticulo', '0004_auto_20180709_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechadereserva',
            name='id',
            field=models.CharField(default='453bd79167b042c59f8c634d749516f5', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default='b99f03fc5e12416d8d3f6684b1d69ad4', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
