# Generated by Django 2.0.3 on 2018-07-09 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaArticulo', '0005_auto_20180709_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechadereserva',
            name='fDate',
            field=models.CharField(default='', max_length=150, validators=[django.core.validators.MinValueValidator('09:00'), django.core.validators.MaxValueValidator('18:00')]),
        ),
        migrations.AlterField(
            model_name='fechadereserva',
            name='fTime',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='fechadereserva',
            name='iDate',
            field=models.CharField(default='', max_length=150, validators=[django.core.validators.MinValueValidator('09:00'), django.core.validators.MaxValueValidator('18:00')]),
        ),
        migrations.AlterField(
            model_name='fechadereserva',
            name='iTime',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='fechadereserva',
            name='id',
            field=models.CharField(default='a73429069def4e5b9f5f4cdc5212f15a', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default='8696e13faba9484485a9e6e025855fa2', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
