# Generated by Django 2.0.5 on 2018-07-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaArticulo', '0005_auto_20180709_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechadereserva',
            name='id',
            field=models.CharField(default='3509594a8b1c436eb4bcb2f1aad54feb', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default='14344d356bdb40efa7591269f889adf8', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
