# Generated by Django 2.0.3 on 2018-07-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaArticulo', '0006_auto_20180709_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechadereserva',
            name='id',
            field=models.CharField(default='4626678383fa46e0a192e388ba364389', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default='768c7b04053b4f6691c549209b9feb29', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, default='media/imagenes/estonoexiste.jpg', null=True, upload_to='imagenes'),
        ),
    ]
