# Generated by Django 2.0.3 on 2018-07-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaArticulo', '0006_auto_20180704_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(upload_to='fichaArticulo/static'),
        ),
    ]
