# Generated by Django 2.0.3 on 2018-07-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaArticulo', '0007_auto_20180709_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechadereserva',
            name='id',
            field=models.CharField(default='3f5cde5d0d4e4822b4d3b34d925dc6fd', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default='9bd70e68af50493ea850d92c4f4f3e5e', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, default='media/imagenes/noimage.png', null=True, upload_to='imagenes'),
        ),
    ]
