# Generated by Django 2.0.5 on 2018-07-10 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichaArticulo', '0008_auto_20180709_2132'),
        ('fichaArticulo', '0006_auto_20180710_0024'),
    ]

    operations = [
    ]
