# Generated by Django 2.0.5 on 2018-07-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaArticulo', '0010_auto_20180710_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechadereserva',
            name='fTime',
            field=models.PositiveSmallIntegerField(choices=[(1, '09:00'), (2, '09:30'), (3, '10:00'), (4, '10:30'), (5, '11:00'), (6, '11:30'), (7, '12:00'), (8, '12:30'), (9, '13:00'), (10, '13:30'), (11, '14:00'), (12, '14:30'), (13, '15:00'), (14, '15:30'), (15, '16:00'), (16, '16:30'), (17, '17:00'), (18, '17:30'), (19, '18:00')], default=''),
        ),
        migrations.AlterField(
            model_name='fechadereserva',
            name='iTime',
            field=models.PositiveSmallIntegerField(choices=[(1, '09:00'), (2, '09:30'), (3, '10:00'), (4, '10:30'), (5, '11:00'), (6, '11:30'), (7, '12:00'), (8, '12:30'), (9, '13:00'), (10, '13:30'), (11, '14:00'), (12, '14:30'), (13, '15:00'), (14, '15:30'), (15, '16:00'), (16, '16:30'), (17, '17:00'), (18, '17:30'), (19, '18:00')], default=''),
        ),
        migrations.AlterField(
            model_name='fechadereserva',
            name='id',
            field=models.CharField(default='3198b4c6fb734abeb0d5c55e4db59b4a', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default='95e34665e51c478ba0e02eb485abf0f0', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
