# Generated by Django 2.0.5 on 2018-07-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaArticulo', '0011_auto_20180710_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechadereserva',
            name='fDate',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='fechadereserva',
            name='iDate',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='fechadereserva',
            name='id',
            field=models.CharField(default='c8c965277e214bf88b917bf839bab942', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default='7c28084f98a3420e9407cb2b69284497', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
