# Generated by Django 2.1a1 on 2018-07-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaArticulo', '0014_auto_20180710_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechadereserva',
            name='id',
            field=models.CharField(default='dc3b8d3b0d634ec3b1e3fc02f92a14a1', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default='fe6fd2ab34284effa9bed0d447861636', editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
