# Generated by Django 2.1a1 on 2018-06-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('description', models.CharField(max_length=200)),
                ('state', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Disponible'), (2, 'En prestamo'), (3, 'Perdido')], null=True)),
            ],
        ),
    ]
