# Generated by Django 2.0.3 on 2018-07-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='img',
        ),
        migrations.AddField(
            model_name='item',
            name='imgfile',
            field=models.ImageField(blank=True, upload_to='images/%m/%d'),
        ),
    ]
