# Generated by Django 2.0.3 on 2018-07-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0005_auto_20180704_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(upload_to='site_media/'),
        ),
    ]
