# Generated by Django 2.0.3 on 2018-07-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0009_auto_20180704_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(blank=True, upload_to='imagenes'),
        ),
    ]
